[workspace]
members = [
    "spark",
    "spark-ds",
    "spark-py",
    "spark-shell",
    "spark-start-master",
    "spark-start-worker",
    "spark-submit",
]

[profile.bench]
debug = true

[profile.release]
debug = true
