[package]
name = "spark-start-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
spark = { path = "../spark" }
tokio = { version = "1.1", features = ["rt-multi-thread", "macros"] }
tarpc = { version = "0.27" }