[package]
name = "spark-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
async-bincode = "0.6.1"
bincode = "1"
futures = "0.3"
rayon = "1"
spark-core = { path = "../spark-core" }
tokio = { version = "1.1", features = ["io-util"] }

