[package]
name = "spark-start-master"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
tracing-subscriber = "0.2"
spark = { path = "../spark" }
tokio = { version = "1.1", features = ["rt-multi-thread", "macros"] }
